repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-yaml
  - id: trailing-whitespace
  - id: end-of-file-fixer
- repo: https://github.com/pseewald/fprettify
  rev: v0.3.3
  hooks:
  - id: fprettify
    args: ['--indent', '2']
    verbose: true
