name: Codecov and testing suite workflow.

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
run:
  runs-on: ubuntu-22.04
  steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Build Suite
        run: |
          cd ./tests \
          ./build_and_compile.sh
      - name: Run tests
        run: mpirun -np 1 ./tests.x
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          gcov: true
          gcov_include: ../src/obj/*.o
